# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-02 02:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=256, verbose_name='Company Name')),
                ('location', models.CharField(blank=True, max_length=128, verbose_name='Location')),
                ('description', models.TextField(blank=True, max_length=2000, verbose_name='Description')),
            ],
        ),
    ]
