# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-02 03:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ep_company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyDivision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_division', models.CharField(max_length=256, verbose_name='Division Name')),
                ('description', models.TextField(blank=True, max_length=2000, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Company Division',
                'verbose_name_plural': 'About Division',
            },
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Company', 'verbose_name_plural': 'About Company'},
        ),
        migrations.AddField(
            model_name='companydivision',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ep_company.Company', verbose_name='Company'),
        ),
    ]
