# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-02 04:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ep_company', '0002_auto_20180302_1029'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySubDivision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_division_name', models.CharField(max_length=256, verbose_name='Sub Division')),
                ('description', models.TextField(blank=True, max_length=2000, verbose_name='Description')),
                ('division_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ep_company.CompanyDivision', verbose_name='Division')),
            ],
            options={
                'verbose_name': 'Sub Division',
                'verbose_name_plural': 'About Sub Division',
            },
        ),
    ]
